export const SITE_URL = "https://www.nexbravesolutions.in";
export const SITE_NAME = "NexBrave Solutions";
export const SITE_DESCRIPTION =
  "NexBrave Solutions is a full-service digital agency building web, app, marketing, SEO and motion work that moves the needle.";

// Shared OG/Twitter image descriptor — the actual image is generated by
// opengraph-image.tsx (Next's file-convention route), this just gives every
// page's metadata an explicit alt text and dimensions for social platforms
// and screen readers, since the file convention alone can't set alt.
export const SITE_OG_IMAGE = {
  url: `${SITE_URL}/opengraph-image`,
  width: 1200,
  height: 630,
  alt: `${SITE_NAME} — full-service digital agency`,
};
